vich_uploader:
    db_driver: orm

    # mappings:
    #     products:
    #         uri_prefix: /images/
    #         upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        carousel:
            uri_prefix: /images/carousel
            upload_destination: '%kernel.project_dir%/public/images/carousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    
        category:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
